### ISSUE TITLE
Update related metadata statements on go-live

### ISSUE THREAD

**Issue by dwsilk** [linz/nz-imagery-surveys#13]
### Description

Provide a link from the abstract on https://data.linz.govt.nz/set/4702-nz-aerial-imagery/, removing this paragraph:

> Imagery is taken between 2000 and 2014. Pixel resolution ranges from 7.5cm (0.075m GSD) to 125cm (1.25m GSD). The final spatial accuracy varies from +/-0.2 m to +/-20m.

**Comment by charlottedawson** [comment]
Done! 
Had to be updated by Ian, as Set datasets require site admin to edit metadata.
https://data.linz.govt.nz/set/4702-nz-aerial-imagery/
