### ISSUE TITLE
Prep list of titles that need to be modified to conform

### ISSUE THREAD

**Issue by dwsilk** [linz/nz-imagery-surveys#21]
### User Story

In order to have consistent layer titles on the LDS, as a data manager I want to **identify** inconsistencies and to confirm the naming convention. 

#### Acceptance Criteria
- [x] Inconsistent spacing is fixed
- [x] Inconsistent year formatting is fixed
- [x] Inconsistent text order is fixed
- [x] Inconsistent hyphen / em-dash usage is fixed
- [x] Naming convention confirmed
- [x] Output contains: Layer id, name of current title and what the problem is.

**Comment by MDavidson17** [comment]
https://gist.github.com/MDavidson17/c1992d4bda423fc1a2c5ad922f742af5

To run, change the username and folder fields in python file
In terminal navigate to folder containing file and enter: `python3 title_updates.py`

**Comment by dwsilk** [comment]
This is great, thanks.
