### ISSUE TITLE
Create animated gif to show timeline of surveys flown

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#24]
### User Story

In order to create blog content to introduce the imagery surveys data, as a data analyst I want to animate the survey data using the flown from and flown to dates on a map.

#### Acceptance Criteria
- [x] Animated gif to introduce on a blog post
- [x] Other content to put in a blog post.
- [ ] ...

**Comment by dwsilk** [comment]
Done, added to Confluence.
