### ISSUE TITLE
Imagery Surveys Layer Geometry and Attribute fixes

### ISSUE THREAD

**Issue by MDavidson17** [linz/nz-imagery-surveys#33]
### User Story

In order to automate the process of updating the NZ Aerial Imagery Set as a LDA I want some issues with the nz-imagery-surveys layer checked and resolved.

#### Acceptance Criteria
- [x] The Southland 0.75m Rural Aerial Photos (2005-2011) Imagery surveys polygon doesn't match the imagery in NZ Aerial Imagery
- [x] Palmerston North 0.1m Urban Aerial Photos (2015) flown_from attribute is (2012-02-15) and the flown to attribute is (2018-02-15), is this correct?

refer #34

**Comment by YingtingChen** [comment]
Updated southland polygon has been put in the `S:\IndependentDatasets\BuildingOutlines\ReferenceData\updated_capture_source_area` folder to replace the one in imagery survey dataset
