### ISSUE TITLE
Raster Calculator not working for Specific Datasets

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-imagery-surveys#34]
### Bug Description

Survey Extent failed to be accurately captured using QGIS Raster Calculator for Christchurch 0.075m Urban Aerial Photos Index Tiles (2015-2016).
Investigate other raster calculators eg gdal

Refer Issue https://github.com/linz/nz-building-outlines/issues/162
![image](https://user-images.githubusercontent.com/15007775/48038111-17001d80-e1d4-11e8-974f-5afca1b07625.png)

**Comment by YingtingChen** [comment]
Updated capture source area polygon has been put in the `S:\IndependentDatasets\BuildingOutlines\ReferenceData\updated_capture_source_area` folder
