### ISSUE TITLE
Evaluate elevation data

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#37]
### User Story

Evaluate whether all datasets have the same attributes, accuracy etc.

#### Acceptance Criteria
- [x] Create a spreadsheet of this summary of indexes
- [x] Talk to Imagery team if there are any format issues
- [x] Determine what the common attributes should say so they are consistent
- [x] Determine consistent data format
- [x] Imagery team to approve

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by Douglas-K** [comment]
Done
