### ISSUE TITLE
Create Data Model

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#39]
### User Story

Create data model for all three layer types: DSM, DEM, Point cloud

#### Acceptance Criteria
- [x] Write SQL for NZ Elevation Survey index
- [x] Include tests to ensure valid schema created
- [x] Confirm data model with Imagery team

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by Douglas-K** [comment]
NZ Elevation Surveys dataset added alongside NZ Imagery Surveys dataset.  Repo to be renamed as NZ Aerial Surveys when ready.
Elevation Surveys added to data dictionary.
