### ISSUE TITLE
Merge 1k tiles 

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#40]
### User Story

Create script to merge 1k tiles

#### Acceptance Criteria
- [x] Create script to merge 1k tiles
- [x] Check for data anomalies 
- [x] Simplify and generalise outlines

**Comment by MDavidson17** [comment]
I have uploaded the script I used to merge/dissolve the 1k tiles here: https://gist.github.com/MDavidson17/380d68785bc2a08654217056f4c33b8e

Attached is a text file containing the counts of vertices for each dissolved survey outline (none of these are too large a number so the geometries have not needed simplifying)
[NumberOfVertices.txt](https://github.com/linz/nz-imagery-surveys/files/3866310/NumberOfVertices.txt)
