### ISSUE TITLE
Create Table and Attribute for LDS

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#41]
### User Story

Create the table and attributes for the LDS

#### Acceptance Criteria
- [x] Create the table with required attributes
- [x] Populate attributes from the source data
- [x] Check with imagery team

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by Douglas-K** [comment]
Sql scripts created.

Update imagery surveys table name, combined ID sequence, and create elevation surveys table:
https://gist.github.com/Douglas-K/9463df0962c82fa76fe41dd69167408b

Populate elevation surveys table:
https://gist.github.com/Douglas-K/138cabb6936afac9d369fa6b6ec84ea2

**Comment by Douglas-K** [comment]
flown_from and flown_to dates are yet to be confirmed for 'Nelson and Tasman' (currently blank)

**Comment by Douglas-K** [comment]
'Nelson and Tasman' dates agreed by Imagery team to be flown_from '2008-01-01' flown_to '2015-12-31'

**Comment by Douglas-K** [comment]
Imagery constraints renamed.  New Waikato - Thames elevation added.

**Comment by Douglas-K** [comment]
Reviewed:Dates corrected for Wellington and Waikato - West Coast and Hauraki Plains.
