### ISSUE TITLE
Publish Layer on LDS

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#43]
### User Story

Publish elevation layer on the LDS

#### Acceptance Criteria
- [x] New dataset request process
- [x] Import data into PostgreSQL
- [x] Scan PostgreSQL database for updates
- [x] Check data after uploading to LDS
- [x] Prep comms for release

**Comment by linzbjones** [comment]
Confirmed with Jonathan about the dataset and completed NZGOAL and Privacy assessment.

Should be good to publish when ready

**Comment by Douglas-K** [comment]
Done
