### ISSUE TITLE
Rename NZ Imagery Surveys to NZ Imagery Survey Index

### ISSUE THREAD

**Issue by dwsilk** [linz/nz-imagery-surveys#44]
### User Story

In order to help users find the NZ Imagery Surveys dataset as a topo data manager I want to rename the dataset to NZ Imagery Survey Index.

#### Acceptance Criteria
- [x] Rename dataset on LDS
- [x] Rename dataset in documentation
- [x] Investigate other places that may need to be renamed

**Comment by Douglas-K** [comment]
Changes scripted for DB table name and Data Dictionary.  Blog looks okay.
Metadata and LDS yet to be done.

**Comment by Douglas-K** [comment]
Database and Data Dictionary updated.
Metadata and LDS updated.
Leaving Blog as it is.
