### ISSUE TITLE
Expand 1:50k tile index as required for coastal mapping

### ISSUE THREAD

**Issue by dwsilk** [linz/nz-imagery-surveys#48]
### User Story

In order to support future mapping in coastal areas, as an LDA I want to expand LINZ's national tile indexes to encompass all locations up to 50m in depth.

#### Acceptance Criteria
- [x] Compare coastal mapping boundary with existing Topo50 map sheets (non-shifted version)
- [x] Add new index tiles to 1:50k tile index
- [x] Add sequence tile name
- [x] Add geometry, output shapefile

**Comment by Douglas-K** [comment]
Expanded 1:50k tile index created:
[50k_index_tiles.zip](https://github.com/linz/nz-imagery-surveys/files/4340357/50k_index_tiles.zip)
