### ISSUE TITLE
Create schema

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#51]
### User Story

In order to create the dataset an an LDA I want to write the SQL to create the schema.

#### Acceptance Criteria
- [x] create 1, 5, 10, 50 k tile tables
- [x] following existing conventions for creating a repo (pgtap)
- [x] define the column names

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment]
Naming is agreed per https://github.com/linz/nz-imagery-surveys/issues/49. So I think the table names should be like:

`aerial_lds.nz_50k_tile_index`

..with these columns:

`index_tile_id`
`map_sheet`
`scale`
`tile`

Haven't thought about data types, happy to discuss once you've had a look at this.

**Comment by dwsilk** [comment]
@rclarkelinz any thoughts on the fields above?

**Comment by rclarkelinz** [comment]
As well as having the tile field, do we also want to have row and column field or is that ott?

**Comment by Douglas-K** [comment]
@rclarkelinz , oh I didn't get an alert even though you mentioned me.  I think having the 'tile : 0405' is enough to represent row and column.  If you need to have row and column columns for the SQL script you can still add/use them temporarily to calculate the tile column
