### ISSUE TITLE
Publish tile indexes to the LDS

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-imagery-surveys#54]
### User Story

In order to provide the public with this amazing dataset, we want to publish it to the LDS.

#### Acceptance Criteria
- [x] Draft comms for Vicki
- [x] Run create schema code, run functions to create tile indexes
- [x] Check database to make sure everything looks good
- [x] Attributes seem to look fine - smaller/larger tiles match each other where they intersect
- [x] Scan database via LDS admin interface
- [x] Fill out NZ goal survey
- [x] Check the new layers in the LDS to make sure everything looks good
- [x] update metadata with correct link ids
- [x] Make public

**Comment by pkinglinz** [comment]
Blurb from Vicki
"
Check out the new 1k, 5k, 10k and 50k Tile Index datasets, providing a consistent scale index you can use across many datasets. Unlike the Topo50 Map sheets, there are no overlapping polygons, and all expand into the sea to areas up to 50m depth to support future coastal mapping.
"

**Comment by dwsilk** [comment]
Tweet still to go out, but our work here is done. :tada:
